// <auto-generated />
using System;
using Bagman.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bagman.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207213336_AddSuperAdminFlag")]
    partial class AddSuperAdminFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bagman.Domain.Models.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_event_types_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_event_types_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_event_types_is_active");

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("match_datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("scheduled")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_matches_id");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("idx_matches_event_type_id");

                    b.HasIndex("MatchDateTime")
                        .HasDatabaseName("idx_matches_datetime");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_pools_id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("idx_pools_match_id");

                    b.ToTable("pools", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.PoolWinner", b =>
                {
                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("AmountWon")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount_won");

                    b.HasKey("PoolId", "UserId")
                        .HasName("pk_pool_winners");

                    b.HasIndex("UserId");

                    b.ToTable("pool_winners", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<bool>("IsSecretMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_secret_mode");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_tables_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_tables_created_by");

                    b.HasIndex("EventTypeId");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_super_admin");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.UserStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<int>("BetsPlaced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bets_placed");

                    b.Property<int>("MatchesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("matches_played");

                    b.Property<int>("PoolsWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pools_won");

                    b.Property<decimal>("TotalWon")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_won");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "TableId")
                        .HasName("pk_user_stats");

                    b.HasIndex("TableId")
                        .HasDatabaseName("idx_user_stats_table_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_stats_user_id");

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("Bagman.Infrastructure.Models.RefreshTokenEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Token")
                        .HasName("pk_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Bagman.Domain.Models.Match", b =>
                {
                    b.HasOne("Bagman.Domain.Models.EventType", "EventType")
                        .WithMany("Matches")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Bagman.Domain.Common.ValueObjects.Score", "Result", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("result");

                            b1.HasKey("MatchId");

                            b1.ToTable("matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsMany("Bagman.Domain.Models.Bet", "Bets", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("EditedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("edited_at");

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid")
                                .HasColumnName("match_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("MatchId")
                                .HasDatabaseName("idx_bets_match_id");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("idx_bets_user_id");

                            b1.HasIndex("UserId", "MatchId")
                                .IsUnique()
                                .HasDatabaseName("uk_bets_user_match");

                            b1.ToTable("bets", (string)null);

                            b1.WithOwner("Match")
                                .HasForeignKey("MatchId");

                            b1.HasOne("Bagman.Domain.Models.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.OwnsOne("Bagman.Domain.Common.ValueObjects.Prediction", "Prediction", b2 =>
                                {
                                    b2.Property<Guid>("BetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("prediction");

                                    b2.HasKey("BetId");

                                    b2.ToTable("bets");

                                    b2.WithOwner()
                                        .HasForeignKey("BetId");
                                });

                            b1.Navigation("Match");

                            b1.Navigation("Prediction")
                                .IsRequired();

                            b1.Navigation("User");
                        });

                    b.OwnsOne("Bagman.Domain.Common.ValueObjects.Country", "Country1", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country_1");

                            b1.HasKey("MatchId");

                            b1.ToTable("matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsOne("Bagman.Domain.Common.ValueObjects.Country", "Country2", b1 =>
                        {
                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country_2");

                            b1.HasKey("MatchId");

                            b1.ToTable("matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Bets");

                    b.Navigation("Country1")
                        .IsRequired();

                    b.Navigation("Country2")
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Bagman.Domain.Models.Pool", b =>
                {
                    b.HasOne("Bagman.Domain.Models.Match", "Match")
                        .WithMany("Pools")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Bagman.Domain.Models.PoolWinner", b =>
                {
                    b.HasOne("Bagman.Domain.Models.Pool", "Pool")
                        .WithMany("Winners")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bagman.Domain.Models.User", "User")
                        .WithMany("PoolWinnings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bagman.Domain.Models.Table", b =>
                {
                    b.HasOne("Bagman.Domain.Models.User", "CreatedByUser")
                        .WithMany("CreatedTables")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bagman.Domain.Models.EventType", "EventType")
                        .WithMany("Tables")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Bagman.Domain.Common.ValueObjects.Money", "Stake", b1 =>
                        {
                            b1.Property<Guid>("TableId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("stake");

                            b1.HasKey("TableId");

                            b1.ToTable("tables");

                            b1.WithOwner()
                                .HasForeignKey("TableId");
                        });

                    b.OwnsOne("Bagman.Domain.Common.ValueObjects.TableName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TableId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TableId");

                            b1.ToTable("tables");

                            b1.WithOwner()
                                .HasForeignKey("TableId");
                        });

                    b.OwnsMany("Bagman.Domain.Models.TableMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("TableId")
                                .HasColumnType("uuid")
                                .HasColumnName("table_id");

                            b1.Property<bool>("IsAdmin")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_admin");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.HasKey("UserId", "TableId");

                            b1.HasIndex("TableId")
                                .HasDatabaseName("idx_table_members_table_id");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("idx_table_members_user_id");

                            b1.ToTable("table_members", (string)null);

                            b1.WithOwner("Table")
                                .HasForeignKey("TableId");

                            b1.HasOne("Bagman.Domain.Models.User", "User")
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Table");

                            b1.Navigation("User");
                        });

                    b.Navigation("CreatedByUser");

                    b.Navigation("EventType");

                    b.Navigation("Members");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Stake")
                        .IsRequired();
                });

            modelBuilder.Entity("Bagman.Domain.Models.UserStats", b =>
                {
                    b.HasOne("Bagman.Domain.Models.Table", "Table")
                        .WithMany("UserStats")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bagman.Domain.Models.User", "User")
                        .WithMany("Stats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bagman.Domain.Models.EventType", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Bagman.Domain.Models.Match", b =>
                {
                    b.Navigation("Pools");
                });

            modelBuilder.Entity("Bagman.Domain.Models.Pool", b =>
                {
                    b.Navigation("Winners");
                });

            modelBuilder.Entity("Bagman.Domain.Models.Table", b =>
                {
                    b.Navigation("UserStats");
                });

            modelBuilder.Entity("Bagman.Domain.Models.User", b =>
                {
                    b.Navigation("CreatedTables");

                    b.Navigation("PoolWinnings");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
